---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://172.16.0.215:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
#monitoring.ui.container.elasticsearch.enabled: false

## X-Pack security credentials
#
#elasticsearch.username: elastic
#elasticsearch.password: 654321aA@